version: '3'
services:
  rabbit:
    image: rabbitmq:3.11-management
    hostname: rabbit
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    container_name: rabbit
volumes:
  rabbitmq_data: